apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: neotys/neoload-controller:{{ .Chart.AppVersion }}
          env:
            - name: MODE
              value: {{ .Values.mode }}
            - name: NEOLOADWEB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: neoload-secrets
                  key: apiToken
            {{ if (.Values.zone) }}
            - name: ZONE
              value: {{ .Values.zone }}
            {{ end }}
            {{ if (.Values.leaseServer) }}
            - name: LEASE_SERVER
              value: {{ .Values.leaseServer }}
            {{ end }}
            {{ if (.Values.nts.url)}}
            - name: NTS_URL
              value: "{{ .Values.nts.url }}"
            {{ end }}
            {{ if (.Values.nts.login) }}
            - name: NTS_LOGIN
              valueFrom:
                secretKeyRef:
                  name: neoload-secrets
                  key: ntsLogin
            {{ end }}
