apiVersion: v1
kind: Secret
metadata:
  name: neoload-secrets
type: Opaque
data:
  apiToken: {{ default "" .Values.apiToken | b64enc | quote }}
  {{ if (.Values.nts.login) }}
  ntsLogin: {{ default "" .Values.nts.login | b64enc | quote }}
  {{ end }}
